level_map = [
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXX1X',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'X2XXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX']

tile_size = 64
TILE_OFFSET = 3
WIDTH_OFFSET, HEIGHT_OFFSET = 85, 85
WIDTH = 1280
HEIGHT = 800

BORDER_X_MIN = 40
BORDER_X_MAX = WIDTH - 140
BORDER_Y_MIN = 40
BORDER_Y_MAX = HEIGHT - 170