level_map = [
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXX2X',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX',
'X1XXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXX']


tile_size = 64
TILE_OFFSET = 3
WIDTH_OFFSET, HEIGHT_OFFSET = 85, 85
WIDTH = 1280
HEIGHT = 800