levels = {
0: [
'CCCCCCCCCCCCRCCC',
'CCCCCCCCCCCCRC2C',
'CCRRRRRRCCCCRCCC',
'CCCCCCCCCCCCCCCC',
'CCCCRCCCCCRCCCCC',
'CCCCCCCCCRRRRCCC',
'CCCRCCCCCCRRCCCC',
'C1CRCCCCCCRCCCCC',
'CCCRCCCCCCCCCCCC'],
1: [
'RCCCCCC  CCCCCCR',
'RRCCCC 12 CCCCRR',
'RRCCCCC  CCCCCRR',
'CCCCCCCCCCCCCCCC',
'CCCRRRRRRRRRRCCC',
'CCCCCCCCCCCCCCCC',
'RRCCCCCCCCCCCCRR',
'RRRCCCCCCCCCCRRR',
'RRRRRCCCCCCRRRRR'],
2: [
'RRCCCCCCRCCCCCRR',
'R1CCCCCRRRCCCC2R',
'RRCCCCCCCCCCCCRR',
'CCCCCCCCCCCCCCCC',
'CCRCCCCCCCCCCCRR',
'CCRCCCCCCRRCCCCC',
'CCCCCCCCCCCCCCCC',
'RRRCCCCRRRCCCRRR',
'RRRCCCCCCCCCCRRR'],
3: [
'CCCCCCCCCCCCRRRR',
'CCCCRCCCCCCCC CR',
'CCCRRRCCCCCCC CR',
'CCCCCCCCCCCCC CC',
'CCCCCC1RR2CCCCCC',
'CCCCCCCCCCCCCCCC',
'C R  CCCCCCCCCCC',
'C RR CCCCC  RRCC',
'C R  CCCCCR   CC'],
4: [
'1  CRCCCCRCCCCRR',
'RRRCRCCCRRRCCCRC',
'CCRCRCCCCRRRCCRC',
'CRRCRRRRCCCCCCCC',
'CCRCRCCCCRRRRRCR',
'CCCCCCRRRRRCCRCR',
'CCRCCCCCCCRCCCCR',
'CRRCRRRRCCRCCRRR',
'CCRCCCRCCCCCC  2']
}


tile_size = 64
TILE_OFFSET = 3
WIDTH_OFFSET, HEIGHT_OFFSET = 85, 85
WIDTH = 1280
HEIGHT = 800

BORDER_X_MIN = 40
BORDER_X_MAX = WIDTH - 140
BORDER_Y_MIN = 40
BORDER_Y_MAX = HEIGHT - 170